#!/bin/bash

#PBS -N 2D_816_SST
#PBS -o 2D_816_SST.out
#PBS -j oe
#PBS -m aeb
#PBS -l nodes=02:ppn=12
#PBS -l walltime=23:59:59


REUSE_DIR=/home/memory/cases/Hyshot_NEW/2D_INFLOW_GENERATION/REUSE
RUN_DIR=/home/memory/cases/Hyshot_NEW/2D_INFLOW_GENERATION/SHOT_816/SST_aoa-3.6_ti0.01

# move into individual run directory
cd $RUN_DIR
  
sed -i 's/{OUTPUT_NAME}/fluid_SST/g' Joe.in

### run JOE ###
cat $PBS_NODEFILE > $RUN_DIR/HOSTS

mpirun_rsh -ssh -np 24 -hostfile $RUN_DIR/HOSTS $REUSE_DIR/joe 11 > output.SST.log 2>&1

wait
rm $RUN_DIR/HOSTS

echo "Finished!"
