#!/bin/bash

#PBS -N 3D_810_C_coarse
#PBS -o 3D_810_C_coarse.out
#PBS -j oe
#PBS -m aeb
#PBS -l nodes=03:ppn=12
#PBS -l walltime=71:59:59

### set up certain directories ###
REUSE_DIR=/home/memory/cases/Hyshot_NEW/3D_COMBUSTOR/REUSE
RUN_DIR=/home/memory/cases/Hyshot_NEW/3D_COMBUSTOR/SHOT_810/COARSE_COLD

# move into individual run directory
cd $RUN_DIR
  
### check for ghost jobs ###
cp $REUSE_DIR/ghost_jobs_script $RUN_DIR/ghost_check

ID=$(echo $PBS_JOBID | sed 's/.certainty.stanford.edu//g')

sed -i 's/JOBID/'$ID'/g' ghost_check
./ghost_check
rm ghost_check

if [ -f ghost_jobs.txt ];
then
  cat ghost_jobs.txt | mail -s "Ghosts on $PBS_JOBNAME" memory@stanford.edu
fi

### run JOE ###
cat $PBS_NODEFILE > $RUN_DIR/HOSTS

mpirun_rsh -ssh -np 36 -hostfile $RUN_DIR/HOSTS $REUSE_DIR/joe 3 > output.SST.log 2>&1
#mpiexec -n 36  $REUSE_DIR/joe 3 > output.SST.log 2>&1

wait
rm $RUN_DIR/HOSTS

echo "Finished!"
